### ISSUE TITLE
Can not clone the code 

### ISSUE THREAD

**Issue by pingyangtiaer** [PacktPublishing/Hands-on-Microservices-with-Python#1]
When I tried to run the following commands:
git clone git@github.com:PacktPublishing/Hands-on-Microservices-with-Python.git frontend.git
git clone git@github.com:PacktPublishing/Hands-on-Microservices-with-Python-User-Service.git user_service.git
git clone git@github.com:PacktPublishing/Hands-on-Microservices-with-Python-Product-Service.git product_service.git
git clone git@github.com:PacktPublishing/Hands-on-Microservices-with-Python-Order-Service.git order_service.git

it gave me the errors:
"""
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
"""
Would you please let me know how to clone the above code?

**Comment by MurtazaTinwala** [comment]
Hi @pingyangtiaer 

It seems your Git is not set up properly as it's not getting connected to the server.
There are 2 methods through which you can connect. 
  1) Connecting over HTTPS (recommended)
  2) Connecting over SSH

Please refer the official documentation: https://help.github.com/articles/set-up-git/

An alternative way which I would recommend is to try using GitHub Desktop application: https://desktop.github.com/

Just setup the application with your credentials and then Clone repository with URL through the interface.

Regards,
