### ISSUE TITLE
error deploying containers - 

### ISSUE THREAD

**Issue by ypbl** [PacktPublishing/Hands-on-Microservices-with-Python#10]
Hi @pfwd 
I found the following error when deploying  docker-compose -f docker-compose.deploy.yml up -d.
The error appears with the product service Dockerfile :

**ERROR: unsatisfiable constraints:
  py-mysqldb (missing):
    required by: world[py-mysqldb]
ERROR: Service 'product' failed to build : The command '/bin/sh -c apk add --update     py-mysqldb     gcc     libc-dev     mariadb-dev     nodejs     npm     && pip install --upgrade pip      && pip install -r requirements.txt     && rm -rf /var/cache/apk/*' returned a non-zero code: 1**

Thanks for your help

**Comment by pfwd** [comment]
@ypbl I have removed `py-mysqldb` and added `build-base` can you try again please

**Comment by ypbl** [comment]
Thanks @pfwd, it works perfectly now.
