### ISSUE TITLE
Not finding the User_Service api code

### ISSUE THREAD

**Issue by pyrobit** [PacktPublishing/Hands-on-Microservices-with-Python#5]
Hi the code is presenting only the API clients in the frontend folder. I was not able to find the api code for the services. Are they in another repo?

**Comment by pfwd** [comment]
Hi @pyrobit please see the readme

> Installation
Read the requirements guide first
To install the whole application read the Microservices installation guide
To install just the frontend read the Frontend installation guide

Here is the [documentation](https://github.com/PacktPublishing/Hands-on-Microservices-with-Python/blob/master/docs/install/microservices.md) for the rest of the application
